_BASE_: "Base-OVD-RCNN-C4.yaml"
MODEL:
  RKD_FEAT_PATH: datasets/clip_proposals/neudet_props/clip_distilfeats
  DISTILLATION: True
  DISTIL_L1_LOSS_WEIGHT: 0.1
  NUM_DISTIL_PROP: 5
  IRM_LOSS_WEIGHT: 0.1
  ROI_BOX_HEAD:
    CAT_FREQ_PATH: 'data/neudet_coco/zero-shot/instances_train2017_seen_2_cat_info.json'
    ZEROSHOT_WEIGHT_DIM: 1024
    ZEROSHOT_WEIGHT_PATH: 'datasets/zeroshot_weights/neudet_clip_a+defect+cname.npy'
  ROI_HEADS:
    NUM_CLASSES: 6
    BATCH_SIZE_PER_IMAGE: 16
OUTPUT_DIR: output/neudet_ovd_RKD
DATASETS:
  TRAIN: ("neudet_zeroshot_train",)
  TEST: ("neudet_test",)


SOLVER:
  IMS_PER_BATCH: 16 # Overall batch-size
  BASE_LR: 0.01  # 降低基础学习率（从0.02降到0.01）
  WARMUP_ITERS: 2000  # 增加预热迭代次数（从1000增到2000）
  WEIGHT_DECAY: 0.0001  # 保持不变
  STEPS: (60000, 80000)  # 保持不变
  CLIP_GRADIENTS:  # 添加梯度裁剪
    ENABLED: true
    CLIP_TYPE: "norm"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0